#!/bin/bash

set -ex

# Check that the PID files are in the right location
for f in kea-dhcp4.kea-dhcp4.pid kea-dhcp6.kea-dhcp6.pid; do
    test -f "/run/kea/$f"
done

# Check that lock files are in the right location
test -f /run/lock/kea/logger_lockfile

# Check dhcp4 server configuration file
kea-dhcp4 -t /etc/kea/kea-dhcp4.conf

# Check dhcp6 server configuration file
kea-dhcp6 -t /etc/kea/kea-dhcp6.conf

# Check control agent API
curl -s -X POST -H "Content-Type: application/json" -d '{ "command": "version-get", "service": [ "dhcp4" ] }' 127.0.0.1:8000 | jq '.[0].text'

# Check control agent API through kea-shell
echo | kea-shell --service dhcp4 --host 127.0.0.1 --port 8000 version-get | jq '.[0].text'
